version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses_db
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 1
  courses-auth-service:
    image: floredenis2001/courses-auth-service:25.09.2024.19.32.36
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - zipkin
  courses-microservice:
    image: floredenis2001/courses-microservice:25.09.2024.19.12.07
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - zipkin
  gateway:
      image: floredenis2001/courses-gateway:25.09.2024.19.33.12
      ports:
      - "8081:8081"
      networks:
      - mynet
      environment:
         SPRING_PROFILES_ACTIVE: docker
      depends_on:
        - zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - mynet
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9411/health || exit 1" ]
      interval: 30s
      timeout: 10s