version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses_db
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 1
  courses-auth-service:
    image: floredenis2001/courses-auth-service:07.08.2024.12.51.44
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  courses-microservice:
    image: floredenis2001/courses-microservice:latest
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      - mysql
  gateway:
      image: floredenis2001/courses-gateway:07.08.2024.13.23.18
      ports:
      - "8081:8082"
      networks:
      - mynet
      environment:
         SPRING_PROFILES_ACTIVE: docker