version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses_db
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 1
  courses-auth-service:
    image: floredenis2001/courses-auth-service:19.09.2024.16.25.00
    networks:
      - mynet
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    depends_on:
      - mysql

    gateway:
      image: floredenis2001/courses-gateway:15.09.2024.15.55.31
      ports: 
      - "8081:8080"
      networks:
      - mynet
      environment:
      SPRING_PROFILES_ACTIVE: docker

  clientapp:
    image: floredenis2001/courses-client:latest
    networks:
      - mynet
    ports:
      - "80:80"
    depends_on:
      - path-pilot-service
    environment:
      - REACT_APP_ENV=prod
  # nginx:
  #   image: floredenis2001/courses-proxy:latest
  #   networks:
  #     - mynet
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - clientapp
  #     - courses-auth-service